---

# Example config

# Kafka brokers as hos:port,host2:port
# kafka_brokers: localhost:9092
kafka_topic: test
kafka_topic_part: 0
message_count: 1000
# Kafka producer config options
kafka_producer_config:
  bootstrap.servers: 10.128.0.20:6667